In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
### sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
## DEFINE VOCAB SIZE
voc_size=10000

In [4]:
## ONE HOT REPRESENTATION

one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

## Apply one_hot() encoding to every sentence in the list 'sent'
## 'for words in sent' loops through each sentence one by one and stores it temporarily in the variable 'words'
## one_hot() converts each word in the current sentence into a unique integer index
## The integers are generated based on the vocabulary size (voc_size)
## The result is stored as a list of lists in 'one_hot_repr'


[[6784, 5246, 7429, 3983],
 [6784, 5246, 7429, 8282],
 [6784, 8536, 7429, 1132],
 [5716, 5677, 6038, 4069, 1125],
 [5716, 5677, 6038, 4069, 2379],
 [150, 6784, 6392, 7429, 271],
 [9126, 8058, 8623, 4069]]

In [5]:
## WORD EMBEDDING REPRESENTATION

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

 

In [6]:
import numpy as np

In [7]:
sent_length = 8

embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedded_docs

## Set the maximum sentence length to 8
## Add 0s at the beginning ('pre') if a sentence is shorter than 8
## Store the padded sentences in 'embedded_docs'


array([[   0,    0,    0,    0, 6784, 5246, 7429, 3983],
       [   0,    0,    0,    0, 6784, 5246, 7429, 8282],
       [   0,    0,    0,    0, 6784, 8536, 7429, 1132],
       [   0,    0,    0, 5716, 5677, 6038, 4069, 1125],
       [   0,    0,    0, 5716, 5677, 6038, 4069, 2379],
       [   0,    0,    0,  150, 6784, 6392, 7429,  271],
       [   0,    0,    0,    0, 9126, 8058, 8623, 4069]], dtype=int32)

In [8]:
## FEATURE REPRESENTATION
dim=10 ## 10 dimensions (10 features)

In [9]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

## Create a Sequential neural network model
## Add an Embedding layer to convert integer indices into dense vectors
## voc_size = vocabulary size, dim = embedding vector size, input_length = sentence length
## Compile the model using Adam optimizer and Mean Squared Error (MSE) loss



In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(embedded_docs )

## Pass the padded sentences through the Embedding layer
## Generate the embedding vector for each word in every sentence
## Return the output embeddings

1/1 [==============================] - 0s 112ms/step


array([[[ 0.01187228, -0.04658612,  0.00534973,  0.04993716,
         -0.01630352,  0.00236724,  0.01476891,  0.02776989,
          0.04267205,  0.02643821],
        [ 0.01187228, -0.04658612,  0.00534973,  0.04993716,
         -0.01630352,  0.00236724,  0.01476891,  0.02776989,
          0.04267205,  0.02643821],
        [ 0.01187228, -0.04658612,  0.00534973,  0.04993716,
         -0.01630352,  0.00236724,  0.01476891,  0.02776989,
          0.04267205,  0.02643821],
        [ 0.01187228, -0.04658612,  0.00534973,  0.04993716,
         -0.01630352,  0.00236724,  0.01476891,  0.02776989,
          0.04267205,  0.02643821],
        [ 0.03600757,  0.03445754, -0.02236356, -0.01871309,
         -0.01566426, -0.00973193, -0.01617946,  0.04947454,
          0.02171761,  0.00749183],
        [ 0.00687896, -0.04791951, -0.01244335, -0.04018011,
         -0.02426961,  0.03642038,  0.00963189,  0.02455107,
         -0.039822  ,  0.04616087],
        [ 0.00827199,  0.00180676,  0.03086646, -0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 6784, 5246, 7429, 3983], dtype=int32)

In [13]:
model.predict(embedded_docs[0] )

### 10 vector vlaues of each gigit becz dim=10 and total 8 array size so 8 words with 10 sector size becz dim =10

1/1 [==============================] - 0s 20ms/step


array([[ 0.01187228, -0.04658612,  0.00534973,  0.04993716, -0.01630352,
         0.00236724,  0.01476891,  0.02776989,  0.04267205,  0.02643821],
       [ 0.01187228, -0.04658612,  0.00534973,  0.04993716, -0.01630352,
         0.00236724,  0.01476891,  0.02776989,  0.04267205,  0.02643821],
       [ 0.01187228, -0.04658612,  0.00534973,  0.04993716, -0.01630352,
         0.00236724,  0.01476891,  0.02776989,  0.04267205,  0.02643821],
       [ 0.01187228, -0.04658612,  0.00534973,  0.04993716, -0.01630352,
         0.00236724,  0.01476891,  0.02776989,  0.04267205,  0.02643821],
       [ 0.03600757,  0.03445754, -0.02236356, -0.01871309, -0.01566426,
        -0.00973193, -0.01617946,  0.04947454,  0.02171761,  0.00749183],
       [ 0.00687896, -0.04791951, -0.01244335, -0.04018011, -0.02426961,
         0.03642038,  0.00963189,  0.02455107, -0.039822  ,  0.04616087],
       [ 0.00827199,  0.00180676,  0.03086646, -0.03025103, -0.04457271,
        -0.02572974, -0.00709249, -0.01369648